"""
Django settings for alx_backend_caching_property_listings project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lgn+7vvi%dd$t2t@wm)lp6z6y-hg&eyho=7o=y!$7%2_bw7i0c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'properties.apps.PropertiesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alx_backend_caching_property_listings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alx_backend_caching_property_listings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # Use PostgreSQL engine
        'ENGINE': 'django.db.backends.postgresql',

        # Database name (must match POSTGRES_DB in docker-compose.yml)
        'NAME': 'property_listings_db',

        # Database user (must match POSTGRES_USER in docker-compose.yml)
        'USER': 'postgres',

        # Database password (must match POSTGRES_PASSWORD in docker-compose.yml)
        'PASSWORD': 'postgres123',

        # Host - use 'localhost' when running Django outside Docker
        # Use 'postgres' (service name) if running Django inside Docker
        'HOST': 'localhost',

        # Port - PostgreSQL default port
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================
# REDIS CACHE CONFIGURATION
# ============================================
CACHES = {
    'default': {
        # Use django-redis as the cache backend
        'BACKEND': 'django_redis.cache.RedisCache',

        # Redis connection URL (host:port/db)
        'LOCATION': 'redis://localhost:6379/1',

        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            # Use pickle serializer for caching HttpResponse objects
            'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',
            'KEY_PREFIX': 'property_listings',
            'IGNORE_EXCEPTIONS': True,
        },

        'TIMEOUT': 300,
    # Use Django's default key function (importable path)
    'KEY_FUNCTION': 'django.core.cache.backends.base.default_key_func',
        'VERSION': 1,
    }
}


# ============================================
# SESSION CONFIGURATION (Use Redis for sessions)
# ============================================
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# ============================================
# LOGGING CONFIGURATION
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Log Django cache operations
        'django.cache': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Log our custom cache metrics
        'properties': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
